# Generated by Django 4.0 on 2021-12-18 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DifficultyModel',
            fields=[
                ('difficulty_id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=500, null=True)),
                ('audio_url', models.CharField(max_length=500, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='CourseApp.coursemodel')),
            ],
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='difficulty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='difficulty', to='CourseApp.difficultymodel'),
        ),
    ]
